Bnpp.Web/Controllers/OnOffDataController.cs
using Bnpp.Core.Convertors;
using Bnpp.Core.Services.Interfaces;
using Bnpp.Core.ViewModels;
using Bnpp.DataLayer.Entities;
using Bnpp.DataLayer.Entities.ONOFF;
using Bnpp.DataLayer.ViewModels;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data.OleDb;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;

namespace Bnpp.Web.Controllers
{
    public class OnOffDataController : Controller
    {
		private IMechanicalService _mechanical;
		private IChangeService _changeService;
		private IConfiguration Configuration;
		public OnOffDataController(IChangeService changeService, IConfiguration _configuration, IMechanicalService mechanical
)
		{
            _mechanical = mechanical;
			Configuration = _configuration;
			_changeService = changeService;
        }

        [BindProperty]
        public ChangeState Change { get; set; }

        [Route("OnOffData/{id}")]
        public IActionResult Index(int id)
        {
            ViewBag.MechanicalId = id;
            ViewData["States"] = _changeService.GetAllStates();
			ViewBag.EquipName = _mechanical.GetEquipmentById(id).Name;

			return View(_changeService.GetAllChangeState());
        }

        public IActionResult CreateOnOffData(int id)
        {
            ViewBag.MechanicalId = id;
            ViewData["States"] = _changeService.GetAllStates();
            return View();
        }

        [HttpPost]
        public IActionResult CreateOnOffData(List<int> SelectedStates, string Dateofchangestate = "")
        {
            //if (!ModelState.IsValid)
            //{
            //    return View();
            //}


            if (Dateofchangestate != "")
            {
                string[] std = Dateofchangestate.Split('/', ' ', ':');
                Change.ChangeStateDate = new DateTime(
                    int.Parse(std[0]),
                    int.Parse(std[1]),
                    int.Parse(std[2]),
                    int.Parse(std[3]),
                    int.Parse(std[4]),
                    int.Parse(std[5]),
                    new GregorianCalendar()
                );
            }

            int changestateId = _changeService.AddChangeState(Change);

            _changeService.AddStateToStaeChanges(changestateId, SelectedStates);



            return RedirectToAction("Index");
        }

        public IActionResult EditOnOffData(int id)
        {
            ViewData["States"] = _changeService.GetAllStates();
            return View(_changeService.GetChangeStateById(id));
        }

        [HttpPost]
        public IActionResult EditOnOffData(List<int> SelectedStates, string Dateofchangestate = "")
        {
            //if (!ModelState.IsValid)
            //{
            //    return View();
            //}


            if (Dateofchangestate != "")
            {
                string[] std = Dateofchangestate.Split('/', ' ', ':');
                Change.ChangeStateDate = new DateTime(
                    int.Parse(std[0]),
                    int.Parse(std[1]),
                    int.Parse(std[2]),
                    int.Parse(std[3]),
                    int.Parse(std[4]),
                    int.Parse(std[5]),
                    new GregorianCalendar()
                );
            }

            _changeService.UpdateChangeState(Change);

            _changeService.EDitStateToStaeChanges(Change.ChangeStateId, SelectedStates);



            return RedirectToAction("Index");
        }

        public IActionResult DeleteOnOffData(string[] operationalId)
        {
            foreach (string id in operationalId)
            {
                _changeService.DeleteChangeState(Convert.ToInt32(id));
            }

            return Json(" Diesel Generators Successfully Deleted.");
        }

        [HttpPost]
        public IActionResult ExportOnOffData(string reportId, int mechanicalId)
        {
            if (reportId == null)
            {
                var chemistryDocument = _changeService.GetAllChangeStateForExport(mechanicalId).ToList();
                using (XLWorkbook wb = new XLWorkbook())
                {

                    var ws = wb.Worksheets.Add(Commons.ToDataTable(chemistryDocument.ToList()));
                    ws.Name = "On-Off data";

                    using (MemoryStream stream = new MemoryStream())
                    {
                        wb.SaveAs(stream);
                        return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "On-Off data.xlsx");
                    }
                }
            }
            else
            {
                var res = new List<OFFViewModel>();

                string[] std = reportId.Split(',');

                foreach (string id in std)
                {
                    var chemistryDocument = _changeService.GetChangeStateByIdForExport(Convert.ToInt32(id));
                    res.Add(chemistryDocument);
                }

                using (XLWorkbook wb = new XLWorkbook())
                {
                    var ws = wb.Worksheets.Add(Commons.ToDataTable(res.ToList()));
                    ws.Name = "On-Off data";
                    using (MemoryStream stream = new MemoryStream())
                    {
                        wb.SaveAs(stream);

                        return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "On-Off data.xlsx");
                    }
                }
            }

        }

        [HttpPost]
        public async Task<IActionResult> ImportOnOffData(IFormFile FormFile, int mechanicalId)
        {
            //get file name
            //var filename = ContentDispositionHeaderValue.Parse(FormFile.ContentDisposition).FileName.Trim('"');
            string filename = Path.GetFileName(FormFile.FileName);
            //get path
            var MainPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Uploads");

            //create directory "Uploads" if it doesn't exists
            if (!Directory.Exists(MainPath))
            {
                Directory.CreateDirectory(MainPath);
            }

            //get file path 
            var filePath = Path.Combine(MainPath, FormFile.FileName);
            using (System.IO.Stream stream = new FileStream(filePath, FileMode.Create))
            {
                await FormFile.CopyToAsync(stream);
            }

            //get extension
            string extension = Path.GetExtension(filename);


            string conString = string.Empty;

            switch (extension)
            {
                case ".xls": //Excel 97-03.
                    conString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR=YES'";
                    break;
                case ".xlsx": //Excel 07 and above.
                    conString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR=YES'";
                    break;
            }

            DataTable dt = new DataTable();
            conString = string.Format(conString, filePath);

            dt.Columns.Add("ChangeStateId", typeof(int));

            using (OleDbConnection connExcel = new OleDbConnection(conString))
            {
                using (OleDbCommand cmdExcel = new OleDbCommand())
                {
                    using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
                    {
                        cmdExcel.Connection = connExcel;

                        //Get the name of First Sheet.
                        connExcel.Open();
                        DataTable dtExcelSchema;
                        dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                        string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                        connExcel.Close();

                        //Read Data from First Sheet.
                        connExcel.Open();
                        cmdExcel.CommandText = "SELECT * From [" + sheetName + "]";
                        odaExcel.SelectCommand = cmdExcel;
                        odaExcel.Fill(dt);

                        // Add new column to table

                        dt.Columns.Add("CreateDate", typeof(DateTime));
                        dt.Columns.Add("IsDelete", typeof(bool));
						dt.Columns.Add("MechanicalId", typeof(int));
						foreach (DataRow row in dt.Rows)
                        {
							// Where I tried to add new value to the column.
							row["MechanicalId"] = mechanicalId;
							row["CreateDate"] = DateTime.Now;
                            row["IsDelete"] = false;
                        }

                        connExcel.Close();
                    }
                }
            }
            //your database connection string
            //conString = @"Data Source=87.236.215.209;Initial Catalog=bnppDBNew;Integrated Security=False;Persist Security Info=False;User ID=bnppuser;Password=1234@qweR1234@qweR";
			conString = this.Configuration.GetConnectionString("BnppConnection");
			using (SqlConnection con = new SqlConnection(conString))
            {
                using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(con))
                {
                    //Set the database table name.
                    sqlBulkCopy.DestinationTableName = "dbo.ChangeState";

                    // Map the Excel columns with that of the database table, this is optional but good if you do


                    sqlBulkCopy.ColumnMappings.Add("Description", "Description");
                    sqlBulkCopy.ColumnMappings.Add("ChangeStateDate", "ChangeStateDate");
					sqlBulkCopy.ColumnMappings.Add("MechanicalId", "MechanicalId");

Bnpp.Web/Views/OnOffData/CreateOnOffData.cshtml
@model Bnpp.DataLayer.Entities.ONOFF.ChangeState
@using Bnpp.DataLayer.Entities.ONOFF
@{
	ViewData["Title"] = "CreateOnOffData";
	Layout = null;
	List<States> permissions = ViewData["States"] as List<States>;
}

<div id="normal">
	<form id="designForm" asp-action="CreateOnOffData" method="post">
		<input type="hidden" asp-for="MechanicalId" value="@ViewBag.MechanicalId" />
		<table cellpadding="3" cellspacing="0">
			<tbody>


				<tr>
					<td>
						Date of change state:
					</td>
					<td>
						<input name="Dateofchangestate" id="Dateofchangestate" style="direction: ltr; text-align: left;">
					</td>
				</tr>

				@foreach (var stte in permissions)
				{
					<li>
						<input type="checkbox" name="SelectedStates" value="@stte.StateId" /> @stte.StateTitle
					</li>
				}

				<tr>
					<td>
						Description:
					</td>
					<td>
						<input asp-for="Description" type="text" style="direction: ltr; text-align: left;">
					</td>
					<td>
						<span asp-validation-for="Description"></span>
					</td>
				</tr>
				<tr>
					<td>
						<input type="submit" @*onclick="AjaxdocumentFormSubmit()"*@ value="Save" class="butn-save" style="direction: ltr; text-align: left;">
						<input type="button" onclick="location='/OnOffData/@ViewBag.MechanicalId'" value="Cancel" id="Button2" class="butn-cancel" style="direction: ltr; text-align: left;">
					</td>
				</tr>
			</tbody>
		</table>
	</form>
</div>


<link href="/css/kendo.common.min.css" rel="stylesheet" />
<link href="/css/kendo.default.min.css" rel="stylesheet" />

<script src="/js/jquery.min.js"></script>
<script src="/js/kendo.all.min.js"></script>
<script src="~/js/jquery.validate.min.js"></script>
<script src="~/js/jquery.validate.unobtrusive.min.js"></script>

<script>

	$("#Dateofchangestate").kendoDateTimePicker(
		{
			format: "yyyy/MM/dd hh:mm:ss"
		});

</script>

Bnpp.Web/Views/OnOffData/EditOnOffData.cshtml
@model Bnpp.DataLayer.ViewModels.ONOFFViewModel
@using Bnpp.DataLayer.Entities.ONOFF
@{
	ViewData["Title"] = "CreateOnOffData";
	Layout = null;
	List<States> statess = ViewData["States"] as List<States>;
}

<div id="normal">
	<form id="designForm" asp-action="EditOnOffData" method="post">
		<input type="hidden" asp-for="ChangeStateId" />
		<input type="hidden" asp-for="@Model.MechanicalId" />
		<table cellpadding="3" cellspacing="0">
			<tbody>


				<tr>
					<td>
						Date of change state:
					</td>
					<td>
						<input name="Dateofchangestate" id="Dateofchangestate" style="direction: ltr; text-align: left;">
					</td>
				</tr>

				<tr>
					@foreach (var p in statess)
					{

						<label>
							<input type="checkbox" name="SelectedStates" value="@p.StateId" @((Model.ChangingInStates.Any(r => r == p.StateId) ? "checked" : ""))>@p.StateTitle
						</label>

					}
				</tr>

				<tr>
					<td>
						Description:
					</td>
					<td>
						<input asp-for="Description" type="text" style="direction: ltr; text-align: left;">
					</td>
					<td>
						<span asp-validation-for="Description"></span>
					</td>
				</tr>
				<tr>
					<td>
						<input type="submit" onclick="if(confirm('Are You sure ?')){}else{return false;};" value="Save" class="butn-save" style="direction: ltr; text-align: left;">
						<input type="button" onclick="location='/OnOffData/@Model.MechanicalId'" value="Cancel" id="Button2" class="butn-cancel" style="direction: ltr; text-align: left;">
					</td>
				</tr>
			</tbody>
		</table>
	</form>
</div>


<link href="/css/kendo.common.min.css" rel="stylesheet" />
<link href="/css/kendo.default.min.css" rel="stylesheet" />

<script src="/js/jquery.min.js"></script>
<script src="/js/kendo.all.min.js"></script>
<script src="~/js/jquery.validate.min.js"></script>
<script src="~/js/jquery.validate.unobtrusive.min.js"></script>

<script>

	$("#Dateofchangestate").kendoDateTimePicker(
		{
			format: "yyyy/MM/dd hh:mm:ss"
		});

</script>

Bnpp.Web/Views/OnOffData/Index.cshtml
@model IEnumerable<Bnpp.DataLayer.ViewModels.ONOFFViewModel>
@using Bnpp.DataLayer.Entities.ONOFF
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
	List<States> statess = ViewData["States"] as List<States>;
}

<div class="dcontent">
	<div style="margin-top: 10px; background-color: #6b8d9e; padding-top: 5px; padding-bottom: 5px; padding-right: 10px; border-radius: 5px; border: solid 1px #cccccc; background: repeating-linear-gradient(-45deg, #7fa1b3, #6b8d9e 1px, #6b8d9e 1px, #6b8d9e 20px);">
		&nbsp;
	</div>

	<div style="border-radius: 5px; margin-top: 5px; margin-bottom: 5px; padding: 15px; border: solid 1px #cea001; background-color: #ffe100;">
		<table cellpadding="3" cellspacing="0">
			<tbody>
				<tr>
					<td style="">
						<b><a class="breadcumb2-link" href="/Equipments">Mechanical Equipments</a></b>
					</td>
					<td style="">
						» @ViewBag.EquipName <b id="subTitle22a"></b>
					</td>


					<td style="">
						» <label>
							<select required="required" onchange="location = this.value;" name="EventLevel" aria-controls="myTable" class="">

								<option value="/OnOffData/@ViewBag.MechanicalId">On-Off Data</option>

								<option value="/Technical/@ViewBag.MechanicalId">BasicData</option>
								<option value="/Documents/@ViewBag.MechanicalId">Documents</option>
								<option value="/AgeingMechanism/@ViewBag.MechanicalId">Ageing Mechanism</option>
								<option value="/Installation/@ViewBag.MechanicalId">Installation & Commissioning</option>
								<option value="/Operational/@ViewBag.MechanicalId">Operational Data</option>
								<option value="/Events/@ViewBag.MechanicalId">Events</option>

								<option value="/Maintenance/@ViewBag.MechanicalId">Maintenance</option>
								<option value="/Inspection/@ViewBag.MechanicalId">Inspection Data</option>
							</select>
						</label>
					</td>
					<td style="">
						» On-Off data<b id="subTitle22a"></b>
					</td>
					<td>
						<b style="color: #ff0000;" id="subTitle22"></b>
					</td>
				</tr>
			</tbody>
		</table>
		<a id="iHelp" style="float: right; position: relative; top: -32px;" href="javascript:;" onclick="showHelp();">
			<img src="/images/help.png" style="width: 48px;" class="imgHelp">
		</a>
	</div>

	<h1 id="iH1">
		On-Off data
	</h1>
	<div id="iContent">



		<div id="tab1" class="tab-item" style="display: block;">



			<div class="bevel-box">
				<table cellpadding="3" cellspacing="0">
					<tbody>
						<tr>
							<td>
								<form method="post" asp-controller="OnOffData" asp-action="ExportOnOffData" asp-route-id="@ViewBag.MechanicalId">
									<input type="number" value="@ViewBag.MechanicalId" name="mechanicalId" style="display:none" />
									<input type="text" id="exportSelectedData" name="reportId" style="display:none" />
									<input type="submit" onclick="refreshPage()" value="Export Excel" />
								</form>
							</td>
							<td>
								<form method="post" asp-controller="OnOffData" asp-action="ImportOnOffData" asp-route-id="@ViewBag.MechanicalId" enctype="multipart/form-data">
									<input type="number" value="@ViewBag.MechanicalId" name="mechanicalId" style="display:none" />
									<input type="file" name="FormFile" />
									<input type="submit" value="Import Excel" />
								</form>
							</td>
						</tr>
					</tbody>
				</table>
			</div>

			<div id="newPage">
				<div>

					<div id="iLoading22" style="display: none;">
						<img src="/images/loading.gif">
					</div>


					<a class="btn-new-equip" style="cursor:pointer" onclick="Create(@ViewBag.MechanicalId)">New</a>
					<input type="button" id="delete" class="btn-delete-equip" value="Delete">
					<br />
					@{
						int rowCount = 1;
					}
					<table id="myTable" cellpadding="3" cellspacing="0" class="show-table">
						<thead>
							<tr role="row">
								<th>
									<input type="checkbox" id="checkAll" />
								</th>
								<th></th>
								<th style="width: 150px">
									<b>Date of change state</b>
								</th>


								<th style="width: 120px">
									<b>Description</b>
								</th>
								<th>

								</th>
								<th style="width: 120px">
									<b>Actions</b>
								</th>
							</tr>
						</thead>
						<tbody>

						
							@foreach (var item in Model)
							{
								<tr role="row">
									<td>
										<input type="checkbox" class="checkBox" value="@item.ChangeStateId" />
									</td>
									<td>
										@rowCount
									</td>

									<td>
										@item.ChangeStateDate.ToString("yyyy/MM/dd HH:mm")
									</td>
									<td>
										@item.Description
									</td>
									<td>
										@foreach (var p in statess)
										{

											<label>
												<input type="checkbox" name="SelectedRoles" value="@p.StateId" @((item.ChangingInStates.Any(r => r == p.StateId) ? "checked" : "")) onclick="return false;">@p.StateTitle
											</label>

										}
									</td>
									<td>
										<a class="btn-edit-equip" onclick="Edit(@item.ChangeStateId)">
											Edit
										</a>
									</td>
								</tr>
								rowCount++;
							}
						</tbody>
					</table>


					<br>
					<div style="clear: both;">
					</div>
					<br>
					<br>
					<iframe style="display: none" id="if_-2_119" src=""></iframe>

				</div>
			</div>
		</div>
	</div>
</div>


@section Scripts{
<script src="/js/jquery.min.js"></script>
<script src="/js/jquery.unobtrusive-ajax.min.js"></script>


<script src="/js/datatables.min.js"></script>


<script>
	$(document).ready(function () {
		$("#myTable").DataTable();
	});
</script>
<script>

		function Create(mechanicalId) {
			$("#newPage").load("/OnOffData/CreateOnOffData/" + mechanicalId);
	}

	function Edit(id) {
		$("#newPage").load("/OnOffData/EditOnOffData/"+id);
	}


	$("#checkAll").click(function () {
		$(".checkBox").prop('checked',
			$(this).prop('checked'));
	});

	$("#delete").click(function () {
		var selectedIDs = new Array();

		$('input:checkbox.checkBox').each(function () {
			if ($(this).prop('checked')) {
				selectedIDs.push($(this).val());
			}
		});


		 var result = confirm("are you sure you want to delete?");
        if (result) {
		$.ajax({
			type: "POST",
					url: "/OnOffData/DeleteOnOffData/@ViewBag.MechanicalId",
			data: { "operationalId": selectedIDs },

			success: function (response) {
						window.location.href = "/OnOffData/@ViewBag.MechanicalId";
			},
			failure: function (response) {
				alert(response.responseText);
			},
			error: function (response) {
				alert(response.responseText);
			}

		});
		}

	});

		$('input:checkbox.checkBox').change(function () {
			var selectedIDs = new Array();
			$('input:checkbox.checkBox').each(function () {
				if ($(this).prop('checked')) {
					selectedIDs.push($(this).val());
				}
			});

			$('#exportSelectedData').val(selectedIDs);

		});

		function refreshPage() {
			// Your delay in milliseconds
			var delay = 2000;
			setTimeout(function () { window.location.href = "/OnOffData/@ViewBag.MechanicalId"; }, delay);
		}

</script>


}