Bnpp.Web/Controllers/ElectromotorController.cs
using System;
using Bnpp.Core.Convertors;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Bnpp.Core.Services.Interfaces;
using Bnpp.Core.ViewModels;
using Bnpp.DataLayer.Entities.Electrical;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Data.SqlClient;
using System.Data.OleDb;
using System.Data;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;

namespace Bnpp.Web.Controllers
{
	public class ElectromotorController : Controller
	{
		private IElectricalService _electrical;
		private IConfiguration Configuration;
		public ElectromotorController(IElectricalService electrical, IConfiguration _configuration)
		{
			Configuration = _configuration;
			_electrical = electrical;
		}

		[Route("Electromotors")]
		public IActionResult Index()
		{
			return View(_electrical.GetAllElectromotos());
		}

		public IActionResult CreateNewElectromotor()
		{
			return View();
		}

		[HttpPost]
		public IActionResult CreateNewElectromotor(ElectromotorsListViewModel electromotor)
		{
			if (!ModelState.IsValid)
			{
				return View(electromotor);
			}

			Electromotors motors = new Electromotors()
			{
				Name = electromotor.Name,
				Azk = electromotor.Azk,
				Position = electromotor.InstalationPosition,
				CreateDate = DateTime.Now
			};

			_electrical.AddElectromotor(motors);

			return RedirectToAction("Index");
		}

		public IActionResult EditElectromotor(int id)
		{
			return View(_electrical.GetElectromotorById(id));
		}

		[HttpPost]
		public IActionResult EditElectromotor(Electromotors electromotor)
		{
			if (!ModelState.IsValid)
			{
				return View(electromotor);
			}
			_electrical.UpdateElectromotor(electromotor);
			return RedirectToAction("Index");
		}

		public IActionResult DeletElectromotor(string[] electromotorId)
		{
			foreach (string id in electromotorId)
			{
				_electrical.DeleteElectromotor(Convert.ToInt32(id));
			}

			return Json(" Electormotors Successfully Deleted.");
		}

		[HttpPost]
		public IActionResult ExportElectromotors(string reportId)
		{
			if (reportId == null)
			{
				var chemistryDocument = _electrical.GetAllElectromotosForExport().ToList();
				using (XLWorkbook wb = new XLWorkbook())
				{
					var ws = wb.Worksheets.Add(Commons.ToDataTable(chemistryDocument.ToList()));
					ws.Name = "Electromotors";

					using (MemoryStream stream = new MemoryStream())
					{
						wb.SaveAs(stream);
						return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Electromotors.xlsx");
					}
				}
			}
			else
			{
				var res = new List<ElectromotorsExportViewModel>();

				string[] std = reportId.Split(',');

				foreach (string id in std)
				{
					var chemistryDocument = _electrical.GetElectromotorByIdExport(Convert.ToInt32(id));
					res.Add(chemistryDocument);
				}

				using (XLWorkbook wb = new XLWorkbook())
				{
					var ws = wb.Worksheets.Add(Commons.ToDataTable(res.ToList()));
					ws.Name = "Electromotors";
					using (MemoryStream stream = new MemoryStream())
					{
						wb.SaveAs(stream);

						return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Electromotors.xlsx");
					}
				}
			}
			//return RedirectToAction("index");
		}

		[HttpPost]
		public async Task<IActionResult> ImportElectromotorsExcelFile(IFormFile FormFile)
		{
			//get file name
			//var filename = ContentDispositionHeaderValue.Parse(FormFile.ContentDisposition).FileName.Trim('"');
			string filename = Path.GetFileName(FormFile.FileName);
			//get path
			var MainPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Uploads");

			//create directory "Uploads" if it doesn't exists
			if (!Directory.Exists(MainPath))
			{
				Directory.CreateDirectory(MainPath);
			}

			//get file path 
			var filePath = Path.Combine(MainPath, FormFile.FileName);
			using (System.IO.Stream stream = new FileStream(filePath, FileMode.Create))
			{
				await FormFile.CopyToAsync(stream);
			}

			//get extension
			string extension = Path.GetExtension(filename);


			string conString = string.Empty;

			switch (extension)
			{
				case ".xls": //Excel 97-03.
					conString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR=YES'";
					break;
				case ".xlsx": //Excel 07 and above.
					conString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR=YES'";
					break;
			}

			DataTable dt = new DataTable();
			conString = string.Format(conString, filePath);

			dt.Columns.Add("ElectromotorId", typeof(int));

			using (OleDbConnection connExcel = new OleDbConnection(conString))
			{
				using (OleDbCommand cmdExcel = new OleDbCommand())
				{
					using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
					{
						cmdExcel.Connection = connExcel;

						//Get the name of First Sheet.
						connExcel.Open();
						DataTable dtExcelSchema;
						dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
						string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
						connExcel.Close();

						//Read Data from First Sheet.
						connExcel.Open();
						cmdExcel.CommandText = "SELECT * From [" + sheetName + "]";
						odaExcel.SelectCommand = cmdExcel;
						odaExcel.Fill(dt);

						// Add new column to table 

						dt.Columns.Add("CreateDate", typeof(DateTime));
						dt.Columns.Add("IsDelete", typeof(bool));

						dt.Columns.Add("Station1", typeof(string));
						dt.Columns.Add("Station2", typeof(string));
						dt.Columns.Add("Type", typeof(string));
						dt.Columns.Add("Position", typeof(string));
						dt.Columns.Add("AzkStruct", typeof(string));
						dt.Columns.Add("ElectromotorImage", typeof(string));
						dt.Columns.Add("BasicImage", typeof(string));

						foreach (DataRow row in dt.Rows)
						{
							// Where I tried to add new value to the column.

							row["CreateDate"] = DateTime.Now;
							row["IsDelete"] = false;


							row["Station1"] = null;
							row["Station2"] = null;
							row["Type"] = null;
							row["Position"] = null;
							row["AzkStruct"] = null;
							row["ElectromotorImage"] = null;
							row["BasicImage"] = null;

						}

						connExcel.Close();
					}
				}
			}
			//your database connection string
			//conString = @"Data Source=87.236.215.209;Initial Catalog=bnppDBNew;Integrated Security=False;Persist Security Info=False;User ID=bnppuser;Password=1234@qweR1234@qweR";
			conString = this.Configuration.GetConnectionString("BnppConnection");
			using (SqlConnection con = new SqlConnection(conString))
			{
				using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(con))
				{
					//Set the database table name.
					sqlBulkCopy.DestinationTableName = "dbo.Electromotors";

					// Map the Excel columns with that of the database table, this is optional but good if you do

					sqlBulkCopy.ColumnMappings.Add("Name", "Name");
					sqlBulkCopy.ColumnMappings.Add("Azk", "Azk");
					sqlBulkCopy.ColumnMappings.Add("Station1", "Station1");
					sqlBulkCopy.ColumnMappings.Add("Station2", "Station2");
					sqlBulkCopy.ColumnMappings.Add("Type", "Type");
					sqlBulkCopy.ColumnMappings.Add("InstalationPosition", "Position");
					sqlBulkCopy.ColumnMappings.Add("AzkStruct", "AzkStruct");
					sqlBulkCopy.ColumnMappings.Add("ElectromotorImage", "ElectromotorImage");
					sqlBulkCopy.ColumnMappings.Add("BasicImage", "BasicImage");


					sqlBulkCopy.ColumnMappings.Add("CreateDate", "CreateDate");
					sqlBulkCopy.ColumnMappings.Add("IsDelete", "IsDelete");

					con.Open();
					sqlBulkCopy.WriteToServer(dt);
					con.Close();
				}
			}
			//if the code reach here means everthing goes fine and excel data is imported into database
			ViewBag.Message = "File Imported and excel data saved into database";

			return RedirectToAction("Index");
			//return Json(" Electormotors Successfully Deleted.");
		}
	}
}

Bnpp.Web/Views/Electromotor/CreateNewElectromotor.cshtml
@model Bnpp.Core.ViewModels.ElectromotorsListViewModel
@{
    ViewData["Title"] = "CreateNewElectromotor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="dcontent">
    <div style="margin-top: 10px; background-color: #6b8d9e; padding-top: 5px; padding-bottom: 5px; padding-right: 10px; border-radius: 5px; border: solid 1px #cccccc; background: repeating-linear-gradient(-45deg, #7fa1b3, #6b8d9e 1px, #6b8d9e 1px, #6b8d9e 20px);">
        &nbsp;
    </div>
    <div style="border-radius: 5px; margin-top: 5px; margin-bottom: 5px; padding: 15px; border: solid 1px #cccccc; background-color: #f0f0f0;">
        <table cellpadding="3" cellspacing="0">
            <tbody>
                <tr>
                    <td>
                        Equip. Type:
                    </td>
                    <td style="width: 300px;">
                        <b>
                            Electrical Equipments
                        </b>
                    </td>
                </tr>
                <tr>
                    <td>
                        &nbsp;
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <h1>Create New Electromotor</h1>

    <div id="iError"></div>
    <form asp-action="CreateNewElectromotor" method="post">
        <table cellpadding="3" cellspacing="0">
            <tbody>
                <tr>
                    <td>
                        Cable Name:
                    </td>
                    <td>
                        <input asp-for="Name" type="text" id="iName" style="direction: ltr; text-align: left;">
                    </td>
                    <td>
                        <span asp-validation-for="Name"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        AKZ:
                    </td>
                    <td>
                        <input asp-for="Azk" type="text" id="iAZK" style="direction: ltr; text-align: left;">
                    </td>
                    <td>
                        <span asp-validation-for="Azk"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        Installation Position:
                    </td>
                    <td>
                        <input asp-for="InstalationPosition" type="text" id="iPosition" style="direction: ltr; text-align: left;">
                    </td>
                    <td>
                        <span asp-validation-for="InstalationPosition"></span>
                    </td>
                </tr>
                <tr style="display: none;">
                    <td>
                        Type:
                    </td>
                    <td>
                        <select name="iType" id="iType" type="text">
                            <option value="پمپ">پمپ</option>
                            <option value="الکتروموتور">الکتروموتور</option>
                            <option value="سیستم های جانبی">سیستم های جانبی</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" value="Save" class="butn-save" style="direction: ltr; text-align: left;">
                        <input type="button" onclick="location='/Electromotors'" value="Cancel" id="Button2" class="butn-cancel" style="direction: ltr; text-align: left;">
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</div>

Bnpp.Web/Views/Electromotor/EditElectromotor.cshtml
@model Bnpp.DataLayer.Entities.Electrical.Electromotors
@{
    ViewData["Title"] = "EditElectromotor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="dcontent">
    <div style="margin-top: 10px; background-color: #6b8d9e; padding-top: 5px; padding-bottom: 5px; padding-right: 10px; border-radius: 5px; border: solid 1px #cccccc; background: repeating-linear-gradient(-45deg, #7fa1b3, #6b8d9e 1px, #6b8d9e 1px, #6b8d9e 20px);">
        &nbsp;
    </div>
    <div style="border-radius: 5px; margin-top: 5px; margin-bottom: 5px; padding: 15px; border: solid 1px #cccccc; background-color: #f0f0f0;">
        <table cellpadding="3" cellspacing="0">
            <tbody>
                <tr>
                    <td>
                        Equip. Type:
                    </td>
                    <td style="width: 300px;">
                        <b>
                            Electrical Equipments
                        </b>
                    </td>
                </tr>
                <tr>
                    <td>
                        &nbsp;
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <h1>Edit Electromotor</h1>

    <div id="iError"></div>
    <form asp-action="EditElectromotor" method="post">
        <input type="hidden" asp-for="ElectromotorId "/>
        <table cellpadding="3" cellspacing="0">
            <tbody>
            <tr>
                <td>
                    Electromotor Name:
                </td>
                <td>
                    <input asp-for="Name" type="text" id="iName" style="direction: ltr; text-align: left;">
                </td>
            </tr>
            <tr>
                <td>
                    AKZ:
                </td>
                <td>
                    <input asp-for="Azk" type="text" id="iAZK" style="direction: ltr; text-align: left;">
                </td>
            </tr>
            <tr>
                <td>
                    Installation Position:
                </td>
                <td>
                    <input asp-for="Position" type="text" id="iPosition" style="direction: ltr; text-align: left;">
                </td>
            </tr>
            <tr style="display: none;">
                <td>
                    Type:
                </td>
                <td>
                    <select name="iType" id="iType" type="text">
                        <option value="پمپ">پمپ</option>
                        <option value="الکتروموتور">الکتروموتور</option>
                        <option value="سیستم های جانبی">سیستم های جانبی</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                        <input onclick="if(confirm('Are You sure ?')){}else{return false;};" type="submit" value="Save" class="butn-save" style="direction: ltr; text-align: left;">
                    <input type="button" onclick="location = '/Electromotors'" value="Cancel" id="Button2" class="butn-cancel" style="direction: ltr; text-align: left;">
                </td>
            </tr>
            </tbody>
        </table>
    </form>
</div>

Bnpp.Web/Views/Electromotor/Index.cshtml
@model IEnumerable<Bnpp.Core.ViewModels.ElectromotorsListViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="dcontent" >
    <div style="margin-top: 10px; background-color: #6b8d9e; padding-top: 5px; padding-bottom: 5px; padding-right: 10px; border-radius: 5px; border: solid 1px #cccccc; background: repeating-linear-gradient(-45deg, #7fa1b3, #6b8d9e 1px, #6b8d9e 1px, #6b8d9e 20px);">
        &nbsp;
    </div>
    <div style="border-radius: 5px; margin-top: 5px; margin-bottom: 5px; padding: 15px; border: solid 1px #cea001; background-color: #ffe100;">
        <table cellpadding="3" cellspacing="0">
            <tbody>
                <tr>
                    <td style="">
                        <b>
                            <a class="breadcumb2-link" href="/DataEntry">Main</a>
                        </b>
                    </td>
                    <td style=""> » <b style="color: #ff0000;"><a class="breadcumb2-link" href="/Electrical">Electrical Equipments</a></b></td>
                </tr>
            </tbody>
        </table><a id="iHelp" style="float: right; position: relative; top: -32px;" href="javascript:;" onclick="showHelp();"><img src="/images/help.png" style="width: 48px;" class="imgHelp"></a>
    </div>

    <h1>Electromotors</h1>

    <div class="bevel-box">
        <table cellpadding="3" cellspacing="0">
            <tbody>
                <tr>

                    <td>
                        <form method="post" asp-controller="Electromotor" asp-action="ExportElectromotors">
                            <input type="text" id="exportSelectedData" name="reportId" style="display:none" />
                            <input type="submit" onclick="refreshPage()" value="Export Excel" />
                        </form>
                    </td>

                    <td>
                        <form method="post" asp-controller="Electromotor" asp-action="ImportElectromotorsExcelFile" enctype="multipart/form-data">
                            <input type="file" name="FormFile" />
                            <input type="submit" value="Import Excel" />
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <a class="btn-new-equip" href="/Electromotor/CreateNewElectromotor">New</a>
    <input type="button" value="Back" onclick="location='/Electrical'" class="butn-cancel" style="direction: ltr; text-align: left;">
    <input type="button" id="delete" class="btn-delete-equip" value="Delete">
    <br />
    @{
        int rowCount = 1;
    }
    <table id="myTable" cellpadding="3" cellspacing="0" class="show-table">
        <thead>
            <tr role="row">
                <th>
                    <input type="checkbox" id="checkAll" />
                </th>
                <th></th>
                <th style="width: 150px">
                    <b>Date</b>
                </th>
                <th style="width: 250px">
                    <b>Electromotor Name</b>
                </th>
                <th style="width: 120px">
                    <b>AKZ Serial</b>
                </th>
                <th style="width: 120px">
                    <b>Instalation Position</b>
                </th>
                <th style="width: 120px">
                    <b>Actions</b>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr role="row">
                    <td>
                        <input type="checkbox" class="checkBox" value="@item.electromotorId" />
                    </td>
                    <td>
                        @rowCount
                    </td>
                    <td>
                        @item.CreateDate.ToString("yyyy/MM/dd")
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Azk
                    </td>
                    <td>
                        @item.InstalationPosition
                    </td>
                    <td>
                        <a class="btn-edit-equip" href="/Electromotor/EditElectromotor/@item.electromotorId">
                            Edit
                        </a>
                    </td>
                </tr>
                rowCount++;
            }
        </tbody>
    </table>
    <br>
</div>


@section Scripts
{

    <script src="/js/jquery.min.js"></script>

    <script src="/js/datatables.min.js"></script>

<script>
    $(document).ready(function () {
        $("#myTable").DataTable();
    });
</script>

<script>
    $("#checkAll").click(function () {
        $(".checkBox").prop('checked',
            $(this).prop('checked'));
    });

    $("#delete").click(function () {
        var selectedIDs = new Array();

        $('input:checkbox.checkBox').each(function () {
            if ($(this).prop('checked')) {
                selectedIDs.push($(this).val());
            }
        });


            var result = confirm("are you sure you want to delete?");
            if (result) {
        $.ajax({
            type: "POST",
            url: "/Electromotor/DeletElectromotor",
            data: { "electromotorId": selectedIDs },



            success: function (response) {
                window.location.href = "/Electromotors";
            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }

        });
        }

    });

        $('input:checkbox.checkBox').change(function () {
            var selectedIDs = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            $('#exportSelectedData').val(selectedIDs);


            //alert(selectedIDs);
        });

        function refreshPage() {
            // Your delay in milliseconds
            var delay = 2000;
            setTimeout(function () { $("#Tabs").load("/Cables/CableReport/"); }, delay);
        }
</script>
    }