Bnpp.Web/Controllers/OperationalController.cs
using Bnpp.Core.Convertors;
using Bnpp.Core.Services;
using Bnpp.Core.Services.Interfaces;
using Bnpp.Core.ViewModels;
using Bnpp.DataLayer.Entities.InspectionData;
using Bnpp.DataLayer.Entities.OperationalDatas;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data.OleDb;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;

namespace Bnpp.Web.Controllers
{
	public class OperationalController : Controller
	{
		private ISensorService _sensor;
		private IConfiguration Configuration;
		private IMechanicalService _mechanical;
		public OperationalController(ISensorService sensor, IConfiguration _configuration, IMechanicalService mechanical
)
		{
			Configuration = _configuration;
			_sensor = sensor;
			_mechanical = mechanical;
		}


		[Route("Operational/{id}")]
		public IActionResult Index(int id)
		{
			ViewBag.MechanicalId = id;
			return View();
		}

		#region Sensors

		[BindProperty]
		public Operational Operational { get; set; }

		public IActionResult Sensors(int id)
		{
			ViewBag.MechanicalId = id;
			ViewBag.EquipName = _mechanical.GetEquipmentById(id).Name;
			return View(_sensor.GetAllSensors(id));
		}

		[HttpPost]
		public IActionResult ExportSensors(string reportId, int mechanicalId)
		{
			if (reportId == null)
			{
				var chemistryDocument = _sensor.GetAllSensorsForExport(mechanicalId).ToList();
				using (XLWorkbook wb = new XLWorkbook())
				{

					var ws = wb.Worksheets.Add(Commons.ToDataTable(chemistryDocument.ToList()));
					ws.Name = "Sensors Data";

					using (MemoryStream stream = new MemoryStream())
					{
						wb.SaveAs(stream);
						return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Sensors Data.xlsx");
					}
				}
			}
			else
			{
				var res = new List<SensorViewModel>();

				string[] std = reportId.Split(',');

				foreach (string id in std)
				{
					var chemistryDocument = _sensor.GetSensorByIdForExport(Convert.ToInt32(id));
					res.Add(chemistryDocument);
				}

				using (XLWorkbook wb = new XLWorkbook())
				{
					var ws = wb.Worksheets.Add(Commons.ToDataTable(res.ToList()));
					ws.Name = "Sensors Data";
					using (MemoryStream stream = new MemoryStream())
					{
						wb.SaveAs(stream);

						return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Sensors Data.xlsx");
					}
				}
			}

		}

		[HttpPost]
		public async Task<IActionResult> ImportSensors(IFormFile FormFile, int mechanicalId)
		{
			//get file name
			//var filename = ContentDispositionHeaderValue.Parse(FormFile.ContentDisposition).FileName.Trim('"');
			string filename = Path.GetFileName(FormFile.FileName);
			//get path
			var MainPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Uploads");

			//create directory "Uploads" if it doesn't exists
			if (!Directory.Exists(MainPath))
			{
				Directory.CreateDirectory(MainPath);
			}

			//get file path 
			var filePath = Path.Combine(MainPath, FormFile.FileName);
			using (System.IO.Stream stream = new FileStream(filePath, FileMode.Create))
			{
				await FormFile.CopyToAsync(stream);
			}

			//get extension
			string extension = Path.GetExtension(filename);


			string conString = string.Empty;

			switch (extension)
			{
				case ".xls": //Excel 97-03.
					conString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR=YES'";
					break;
				case ".xlsx": //Excel 07 and above.
					conString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR=YES'";
					break;
			}

			DataTable dt = new DataTable();
			conString = string.Format(conString, filePath);

			dt.Columns.Add("OperationalId", typeof(int));

			using (OleDbConnection connExcel = new OleDbConnection(conString))
			{
				using (OleDbCommand cmdExcel = new OleDbCommand())
				{
					using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
					{
						cmdExcel.Connection = connExcel;

						//Get the name of First Sheet.
						connExcel.Open();
						DataTable dtExcelSchema;
						dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
						string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
						connExcel.Close();

						//Read Data from First Sheet.
						connExcel.Open();
						cmdExcel.CommandText = "SELECT * From [" + sheetName + "]";
						odaExcel.SelectCommand = cmdExcel;
						odaExcel.Fill(dt);

						// Add new column to table  

						dt.Columns.Add("CreateDate", typeof(DateTime));
						dt.Columns.Add("IsDelete", typeof(bool));
						dt.Columns.Add("ParameterName", typeof(string));
						dt.Columns.Add("TypeId", typeof(int));
						dt.Columns.Add("MechanicalId", typeof(int));
						foreach (DataRow row in dt.Rows)
						{
							// Where I tried to add new value to the column.
							row["MechanicalId"] = mechanicalId;
							row["CreateDate"] = DateTime.Now;
							row["IsDelete"] = false;
							row["ParameterName"] = null;
							row["TypeId"] = 1;
						}

						connExcel.Close();
					}
				}
			}
			//your database connection string
			//conString = @"Data Source=87.236.215.209;Initial Catalog=bnppDBNew;Integrated Security=False;Persist Security Info=False;User ID=bnppuser;Password=1234@qweR1234@qweR";
			conString = this.Configuration.GetConnectionString("BnppConnection");
			using (SqlConnection con = new SqlConnection(conString))
			{
				using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(con))
				{
					//Set the database table name.
					sqlBulkCopy.DestinationTableName = "dbo.Operationals";

					// Map the Excel columns with that of the database table, this is optional but good if you do


					sqlBulkCopy.ColumnMappings.Add("ParameterName", "ParameterName");
					sqlBulkCopy.ColumnMappings.Add("TypeId", "TypeId");
					sqlBulkCopy.ColumnMappings.Add("SensorName", "SensorName");
					sqlBulkCopy.ColumnMappings.Add("AKZ", "AKZ");
					sqlBulkCopy.ColumnMappings.Add("MinimumValue", "MinimumValue");
					sqlBulkCopy.ColumnMappings.Add("MaximumValue", "MaximumValue");
					sqlBulkCopy.ColumnMappings.Add("NormalValue", "NormalValue");
					sqlBulkCopy.ColumnMappings.Add("TransientEvents", "TransientEvents");
					sqlBulkCopy.ColumnMappings.Add("Unit", "Unit");
					sqlBulkCopy.ColumnMappings.Add("MechanicalId", "MechanicalId");

					sqlBulkCopy.ColumnMappings.Add("CreateDate", "CreateDate");
					sqlBulkCopy.ColumnMappings.Add("IsDelete", "IsDelete");

					con.Open();
					sqlBulkCopy.WriteToServer(dt);
					con.Close();
				}
			}
			//if the code reach here means everthing goes fine and excel data is imported into database
			ViewBag.Message = "File Imported and excel data saved into database";

			return RedirectToAction("Index", new { id = mechanicalId });
			//return Json(" Electormotors Successfully Deleted.");
		}

		public IActionResult CraeteSensors(int id)
		{
			ViewBag.MechanicalId = id;
			return View();
		}

		[HttpPost]
		public IActionResult CraeteSensors(Operational sensor)
		{
			//if (!ModelState.IsValid)
			//    return View();

			_sensor.AddSensor(Operational);
			return new JsonResult("success");
		}

		public IActionResult EditSensors(int id)
		{
			return View(_sensor.GetSensorById(id));
		}

		[HttpPost]
		public IActionResult EditSensors()
		{
			//if (!ModelState.IsValid)
			//    return View();

			_sensor.UpdateSensor(Operational);
			return new JsonResult("success");
		}

		public IActionResult DeleteSensors(string[] sensorId)
		{
			foreach (string id in sensorId)
			{
				_sensor.DeleteSensor(Convert.ToInt32(id));
			}
			return new JsonResult("success");
		}
		#endregion

		#region Chemical Water


		public IActionResult ChemicalWater(int id)
        {
            ViewBag.MechanicalId = id;
			ViewBag.EquipName = _mechanical.GetEquipmentById(id).Name;
			return View(_sensor.GetAllChemicalWater(id));
		}



		[HttpPost]
		public IActionResult ExportChemicalWater(string reportId, int mechanicalId)
		{
			if (reportId == null)
			{
				var chemistryDocument = _sensor.GetAllChemicalWaterForExport(mechanicalId).ToList();
				using (XLWorkbook wb = new XLWorkbook())
				{

					var ws = wb.Worksheets.Add(Commons.ToDataTable(chemistryDocument.ToList()));
					ws.Name = "Chemical Water Data";

					using (MemoryStream stream = new MemoryStream())
					{
						wb.SaveAs(stream);
						return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Chemical Water Data.xlsx");
					}
				}
			}
			else
			{
				var res = new List<ChemicalWaterViewModel>();

				string[] std = reportId.Split(',');

				foreach (string id in std)
				{
					var chemistryDocument = _sensor.GetChemicalWaterByIdForExport(Convert.ToInt32(id));
					res.Add(chemistryDocument);
				}

				using (XLWorkbook wb = new XLWorkbook())
				{
					var ws = wb.Worksheets.Add(Commons.ToDataTable(res.ToList()));
					ws.Name = "Chemical Water Data";
					using (MemoryStream stream = new MemoryStream())
					{
						wb.SaveAs(stream);

						return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Chemical Water Data.xlsx");
					}
				}
			}

		}

		[HttpPost]
		public async Task<IActionResult> ImportChemicalWater(IFormFile FormFile, int mechanicalId)
		{
			//get file name
			//var filename = ContentDispositionHeaderValue.Parse(FormFile.ContentDisposition).FileName.Trim('"');
			string filename = Path.GetFileName(FormFile.FileName);
			//get path
			var MainPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Uploads");

			//create directory "Uploads" if it doesn't exists
			if (!Directory.Exists(MainPath))
			{
				Directory.CreateDirectory(MainPath);
			}

			//get file path 
			var filePath = Path.Combine(MainPath, FormFile.FileName);

Bnpp.Web/Views/Operational/ChemicalWater.cshtml
@model IEnumerable<Bnpp.DataLayer.Entities.OperationalDatas.Operational>
@{
    ViewData["Title"] = "ChemicalWater";
    Layout = null;
}

<div class="dcontent">
    <div style="margin-top: 10px; background-color: #6b8d9e; padding-top: 5px; padding-bottom: 5px; padding-right: 10px; border-radius: 5px; border: solid 1px #cccccc; background: repeating-linear-gradient(-45deg, #7fa1b3, #6b8d9e 1px, #6b8d9e 1px, #6b8d9e 20px);">
        &nbsp;
    </div>

    <div style="border-radius: 5px; margin-top: 5px; margin-bottom: 5px; padding: 15px; border: solid 1px #cea001; background-color: #ffe100;">
        <table cellpadding="3" cellspacing="0">
            <tbody>
                <tr>
                    <td style="">
                        <b><a class="breadcumb2-link" href="/Equipments">Mechanical Equipments</a></b>
                    </td>
                    <td style="">
                        » @ViewBag.EquipName <b id="subTitle22a"></b>
                    </td>


                    <td style="">
                        » <label>
                            <select required="required" onchange="location = this.value;" name="EventLevel" aria-controls="myTable" class="">

                                <option value="/Operational/@ViewBag.MechanicalId">Operational Data</option>

                                <option value="/Technical/@ViewBag.MechanicalId">BasicData</option>
                                <option value="/Documents/@ViewBag.MechanicalId">Documents</option>
                                <option value="/AgeingMechanism/@ViewBag.MechanicalId">Ageing Mechanism</option>
                                <option value="/Installation/@ViewBag.MechanicalId">Installation & Commissioning</option>

                                <option value="/Events/@ViewBag.MechanicalId">Events</option>
                                <option value="/OnOffData/@ViewBag.MechanicalId">On-Off Data</option>
                                <option value="/Maintenance/@ViewBag.MechanicalId">Maintenance</option>
                                <option value="/Inspection/@ViewBag.MechanicalId">Inspection Data</option>
                            </select>
                        </label>
                    </td>
                    <td>
                        » <b style="color: #ff0000;" id="subTitle22">
                            Chemical Water Data
                        </b>
                    </td>
                </tr>
            </tbody>
        </table>
        <a id="iHelp" style="float: right; position: relative; top: -32px;" href="javascript:;" onclick="showHelp();">
            <img src="/images/help.png" style="width: 48px;" class="imgHelp">
        </a>
    </div>

    <h1 id="iH1">
        Operational Data
    </h1>
    <div id="iContent">

        <div class="tab-buttons">
            <ul>
                <li id="tab-button1" class="tab-buttons-li" @*style="background-color: rgb(240, 240, 240); border-color: rgb(192, 192, 192); font-weight: normal;"*@ @*style="background-color: rgb(208, 208, 208); border-color: rgb(128, 128, 128); font-weight: bold;"*@>
                    <a id="tab-button-a1"
                       onclick="showPage1()" style="cursor:pointer;color: rgb(0, 113, 158);">
                        Sensors Data
                    </a>
                </li>
                <li id="tab-button2" @*class="tab-buttons-li"*@ style="background-color: rgb(208, 208, 208); border-color: rgb(128, 128, 128); font-weight: bold;">
                    <a id="tab-buttona2" onclick="showPage2()" style="cursor:pointer;color: rgb(110, 110, 255);">
                        Water Chemical Data
                    </a>
                </li>
                <li id="tab-button3" class="tab-buttons-li" style="background-color: rgb(240, 240, 240); border-color: rgb(192, 192, 192); font-weight: normal;">
                    <a id="tab-button-a3" onclick="showPage3()" style="cursor:pointer;color: rgb(110, 110, 255);">
                        Environmental Data
                    </a>
                </li>
            </ul>

            <div style="clear:both;"></div>
        </div>

        <div id="tab1" class="tab-item" style="display: block;">

            <h1 id="iH1">
                Chemical Water Data
            </h1>

            <div class="bevel-box">
                <table cellpadding="3" cellspacing="0">
                    <tbody>
                        <tr>
                            <td>
                                <form method="post" asp-controller="Operational" asp-action="ExportChemicalWater" asp-route-id="@ViewBag.MechanicalId">
                                    <input type="number" value="@ViewBag.MechanicalId" name="mechanicalId" style="display:none" />
                                    <input type="text" id="exportSelectedData" name="reportId" style="display:none" />
                                    <input type="submit" onclick="refreshPage()" value="Export Excel" />
                                </form>
                            </td>
                            <td>
                                <form method="post" asp-controller="Operational" asp-action="ImportChemicalWater" asp-route-id="@ViewBag.MechanicalId" enctype="multipart/form-data">
                                    <input type="number" value="@ViewBag.MechanicalId" name="mechanicalId" style="display:none" />
                                    <input type="file" name="FormFile" />
                                    <input type="submit" onclick="refreshPage()" value="Import Excel" />
                                </form>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div id="newPage">
                <div>

                    <div id="iLoading22" style="display: none;">
                        <img src="/images/loading.gif">
                    </div>


                    <a class="btn-new-equip" style="cursor:pointer" onclick="Create(@ViewBag.MechanicalId)">New</a>
                    <input type="button" id="delete" class="btn-delete-equip" value="Delete">
                    <br />
                    @{
                        int rowCount = 1;
                    }
                    <table id="myTable" cellpadding="3" cellspacing="0" class="show-table">
                        <thead>
                            <tr role="row">
                                <th>
                                    <input type="checkbox" id="checkAll" />
                                </th>
                                <th></th>
                                <th>
                                    <b>Parameter Name</b>
                                </th>
                                <th>
                                    <b>AKZ</b>
                                </th>
                                <th>
                                    <b>Unit</b>
                                </th>

                                <th>
                                    <b>Minimum</b>
                                </th>

                                <th>
                                    <b>	Maximum</b>
                                </th>
                                <th>
                                    <b>	Normal Value</b>
                                </th>
                                <th>
                                    <b>No. Allowable Transient Events</b>
                                </th>
                                <th>
                                    <b>Actions</b>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr role="row">
                                    <td>
                                        <input type="checkbox" class="checkBox" value="@item.OperationalId" />
                                    </td>
                                    <td>
                                        @rowCount
                                    </td>
                                    <td>
                                        @item.ParameterName
                                    </td>
                                    <td>
                                        @item.AKZ
                                    </td>
                                    <td>
                                        @item.Unit
                                    </td>
                                    <td>
                                        @item.MinimumValue
                                    </td>
                                    <td>
                                        @item.MaximumValue
                                    </td>
                                    <td>
                                        @item.NormalValue
                                    </td>

                                    <td>
                                        @item.TransientEvents
                                    </td>
                                    <td>
                                        <a class="btn-edit-equip" onclick="Edit(@item.OperationalId)">
                                            Edit
                                        </a>
                                    </td>
                                </tr>
                                rowCount++;
                            }
                        </tbody>
                    </table>

                    <br>
                   @*  <input type="button" value="Sensor Positions" onclick="WaterSensorDocument()" class="butn-sensor-position" style="direction: ltr; text-align: left;"> *@

                </div>
            </div>
        </div>
    </div>
</div>

<script src="/js/jquery.min.js"></script>
<script src="/js/jquery.unobtrusive-ajax.min.js"></script>


<script src="/js/datatables.min.js"></script>


<script>
    $(document).ready(function () {
        $("#myTable").DataTable();
    });
</script>
<script>

    function Create(mechanicalId) {
        $("#newPage").load("/Operational/CraeteChemicalWater/" + mechanicalId);
    }

    function Edit(id) {
        $("#newPage").load("/Operational/EditChemicalWater/" + id);
    }


    function showPage1() {
        $("#Tabs").load("/Operational/Sensors/@ViewBag.MechanicalId");
    }

    function showPage2() {
        $("#Tabs").load("/Operational/ChemicalWater/@ViewBag.MechanicalId");
    }

    function showPage3() {
        $("#Tabs").load("/Operational/Environmental/@ViewBag.MechanicalId");
    }


    $("#checkAll").click(function () {
        $(".checkBox").prop('checked',
            $(this).prop('checked'));
    });

    $("#delete").click(function () {
        var selectedIDs = new Array();

        $('input:checkbox.checkBox').each(function () {
            if ($(this).prop('checked')) {
                selectedIDs.push($(this).val());
            }
        });


        var result = confirm("are you sure you want to delete?");
        if (result) {
            $.ajax({
                type: "POST",
                url: "/Operational/DeleteChemicalWater/@ViewBag.MechanicalId",
                data: { "chemicalId": selectedIDs },

                success: function (response) {
                    $("#Tabs").load("/Operational/ChemicalWater/@ViewBag.MechanicalId");
                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }

            });
        }

    });

    function WaterSensorDocument() {
        $("#newPage").load("/Operational/WaterSensorDocument/");
    }

    $('input:checkbox.checkBox').change(function () {
        var selectedIDs = new Array();
        $('input:checkbox.checkBox').each(function () {
            if ($(this).prop('checked')) {
                selectedIDs.push($(this).val());
            }
        });

        $('#exportSelectedData').val(selectedIDs);

    });

    function refreshPage() {
        // Your delay in milliseconds
        var delay = 2000;
        setTimeout(function () { $("#Tabs").load("/Operational/ChemicalWater/@ViewBag.MechanicalId"); }, delay);
    }
</script>

Bnpp.Web/Views/Operational/CraeteChemicalWater.cshtml
@model Bnpp.DataLayer.Entities.OperationalDatas.Operational
@{
    ViewData["Title"] = "CraeteChemicalWater";
    Layout = null;
}

<div id="normal">
    <form id="normalForm" asp-action="CraeteChemicalWater" method="post">
        <input type="hidden" asp-for="MechanicalId" value="@ViewBag.MechanicalId" />
        <table cellpadding="3" cellspacing="0">
            <tbody>
                <tr>
                    <td>
                        Parameter Name:
                    </td>
                    <td>
                        <input asp-for="ParameterName" type="text" id="iName" style="direction: ltr; text-align: left;">
                    </td>
                    <td>
                        <span asp-validation-for="ParameterName"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        AKZ:
                    </td>
                    <td>
                        <input asp-for="AKZ" type="text" id="iAZK" required="" style="direction: ltr; text-align: left;">
                    </td>
                    <td>
                        <span asp-validation-for="AKZ"></span>
                    </td>
                </tr>

                <tr>
                    <td>
                        Minimum Value:
                    </td>
                    <td>
                        <input asp-for="MinimumValue" type="text" id="iAZK" required="" style="direction: ltr; text-align: left;">
                    </td>
                    <td>
                        <span asp-validation-for="MinimumValue"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        Maximum Value:
                    </td>
                    <td>
                        <input asp-for="MaximumValue" type="text" id="iPosition" style="direction: ltr; text-align: left;">
                    </td>
                    <td>
                        <span asp-validation-for="MaximumValue"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        Normal Value:
                    </td>
                    <td>
                        <input asp-for="NormalValue" type="text" id="iPosition" style="direction: ltr; text-align: left;">
                    </td>
                    <td>
                        <span asp-validation-for="NormalValue"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        No. Allowable Transient Events:
                    </td>
                    <td>
                        <input asp-for="TransientEvents" type="text" id="iPosition" style="direction: ltr; text-align: left;">
                    </td>
                    <td>
                        <span asp-validation-for="TransientEvents"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        Unit:
                    </td>
                    <td>
                        <input asp-for="Unit" type="text" id="iPosition" style="direction: ltr; text-align: left;">
                    </td>
                    <td>
                        <span asp-validation-for="Unit"></span>
                    </td>
                </tr>

                <tr>
                    <td>
                        <input type="button" onclick="submitNormal()" value="Save" class="butn-save" style="direction: ltr; text-align: left;">
                        <input type="button" onclick="showPage2()" value="Cancel" id="Button2" class="butn-cancel" style="direction: ltr; text-align: left;">
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</div>

<link href="/css/kendo.common.min.css" rel="stylesheet" />
<link href="/css/kendo.default.min.css" rel="stylesheet" />

<script src="/js/jquery.min.js"></script>
<script src="/js/kendo.all.min.js"></script>
<script src="~/js/jquery.validate.min.js"></script>
<script src="~/js/jquery.validate.unobtrusive.min.js"></script>


<script type="text/javascript">
    function submitNormal() {
        var data = $("#normalForm").serialize();
        var url = $("#normalForm").attr("action");
        $.ajax({
            type: 'POST',
            url: url,
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8', // when we use .serialize() this generates the data in query string format. this needs the default contentType (default content type is: contentType: 'application/x-www-form-urlencoded; charset=UTF-8') so it is optional, you can remove it
            data: data,
            success: function () {
                $("#Tabs").load("/Operational/ChemicalWater/@ViewBag.MechanicalId");
            },

            error: function () {
                //alert('Failed to receive the Data');
                //console.log('Failed ');
            }
        });

    }

</script>

Bnpp.Web/Views/Operational/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="Tabs">

</div>

@section Scripts
{
    <script src="/js/jquery.unobtrusive-ajax.min.js"></script>
    <script>

    $( document ).ready(function() {
            $("#Tabs").load("/Operational/Sensors/@ViewBag.MechanicalId");
    });

    function showPage1() {
            $("#Tabs").load("/Operational/Sensors/@ViewBag.MechanicalId");
    }

    function showPage2() {
            $("#Tabs").load("/Operational/ChemicalWater/@ViewBag.MechanicalId");
        
    }

    function showPage3() {
            $("#Tabs").load("/Operational/Environmental/@ViewBag.MechanicalId");
    }

</script>

}